name: flutter_json_schema
description: Generate a Flutter form based on JSON Schema
version: 0.0.1
homepage: https://github.com/HomeXLabs/flutter-json-schema

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  rxdart: ^0.20.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
